// VALID DATA
export const VALID_CUSTOMER_ID = '1234567890';
export const VALID_CUSTOMER_ID_SHORT = '123456';


// INVALID DATA
export const INVALID_CUSTOMER_ID_CHARACTERS = 'bsbs';
export const INVALID_CUSTOMER_ID_ALPHANUMERIC = '4343jdf';
export const INVALID_CUSTOMER_ID_SPECIAL = '@#$457852';
export const EMPTY_CUSTOMER_ID = '';